trace-cmd: update to 2.4.2
fixes compile error:
(observed w. target arm64, all kernel build opts enabled)
error: call to '__open_missing_mode' declared with attribute
error: open with O_CREAT in second argument needs 3 arguments

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>

git-svn-id: svn://svn.openwrt.org/openwrt/trunk@45625 3c298f89-4303-0410-b956-a3cf2f4a3e73